# Generated by Django 5.2.17 on 2026-10-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WineStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True, verbose_name="nyckel")),
                ("name", models.CharField(max_length=100, verbose_name="namn")),
                (
                    "colour",
                    models.CharField(
                        choices=[
                            ("sparkling", "Mousserande"),
                            ("white", "Vitt"),
                            ("rose", "Rosé"),
                            ("red", "Rött"),
                            ("sweet", "Sött"),
                            ("fortified", "Starkvin"),
                        ],
                        max_length=10,
                        verbose_name="typ",
                    ),
                ),
                (
                    "body",
                    models.PositiveSmallIntegerField(verbose_name="fyllighet (1-5)"),
                ),
                (
                    "acidity",
                    models.PositiveSmallIntegerField(verbose_name="syra (1-5)"),
                ),
                (
                    "tannin",
                    models.PositiveSmallIntegerField(verbose_name="strävhet (1-5)"),
                ),
                (
                    "sweetness",
                    models.PositiveSmallIntegerField(verbose_name="sötma (1-5)"),
                ),
                (
                    "grapes",
                    models.CharField(blank=True, max_length=200, verbose_name="druvor"),
                ),
                (
                    "regions",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="regioner"
                    ),
                ),
                (
                    "pairs_with",
                    models.CharField(
                        blank=True,
                        help_text="Profilnycklar, mellanslagsseparerade.",
                        max_length=300,
                        verbose_name="passar till",
                    ),
                ),
            ],
            options={
                "verbose_name": "vinstil",
                "verbose_name_plural": "vinstilar",
                "ordering": ["colour", "body", "name"],
            },
        ),
        migrations.CreateModel(
            name="RecipeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_component",
                    models.CharField(
                        choices=[
                            ("beef", "Nötkött"),
                            ("lamb", "Lamm"),
                            ("pork", "Fläsk"),
                            ("poultry", "Fågel"),
                            ("game", "Vilt"),
                            ("fish", "Fisk"),
                            ("shellfish", "Skaldjur"),
                            ("charcuterie", "Chark"),
                            ("vegetables", "Grönsaker"),
                            ("mushrooms", "Svamp"),
                            ("pasta", "Pasta, ris eller pizza"),
                            ("cheese", "Ost"),
                            ("dessert", "Dessert"),
                            ("chocolate", "Choklad"),
                        ],
                        max_length=20,
                        verbose_name="huvudingrediens",
                    ),
                ),
                (
                    "cooking_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("raw", "Rå"),
                            ("steamed", "Ångad eller pocherad"),
                            ("fried", "Stekt eller friterad"),
                            ("roasted", "Ugnsstekt"),
                            ("grilled", "Grillad"),
                            ("braised", "Långkok eller gryta"),
                            ("smoked", "Rökt"),
                        ],
                        max_length=20,
                        verbose_name="tillagning",
                    ),
                ),
                (
                    "sauce",
                    models.CharField(
                        choices=[
                            ("none", "Ingen sås"),
                            ("tomato", "Tomat"),
                            ("creamy", "Grädde eller ost"),
                            ("butter", "Smör"),
                            ("asian", "Soja eller asiatisk"),
                            ("spicy", "Stark eller chili"),
                            ("sweet_sour", "Sötsur"),
                            ("citrus", "Citrus"),
                            ("bbq", "BBQ"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="sås",
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        choices=[
                            ("light", "Lätt"),
                            ("medium", "Mellan"),
                            ("heavy", "Mäktig"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="tyngd",
                    ),
                ),
                (
                    "flavours",
                    models.JSONField(blank=True, default=list, verbose_name="smaker"),
                ),
                (
                    "edited_by_user",
                    models.BooleanField(default=False, verbose_name="ändrad för hand"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wine_profile",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "receptprofil",
                "verbose_name_plural": "receptprofiler",
            },
        ),
        migrations.CreateModel(
            name="Pairing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(default=1, verbose_name="ordning"),
                ),
                ("score", models.FloatField(default=0, verbose_name="poäng")),
                ("reason", models.TextField(blank=True, verbose_name="varför")),
                (
                    "source",
                    models.CharField(
                        choices=[("rules", "Regler"), ("ai", "Claude")],
                        default="rules",
                        max_length=10,
                        verbose_name="källa",
                    ),
                ),
                ("rating", models.SmallIntegerField(default=0, verbose_name="betyg")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairings",
                        to="wine.winestyle",
                    ),
                ),
            ],
            options={
                "verbose_name": "vinförslag",
                "verbose_name_plural": "vinförslag",
                "ordering": ["rank"],
                "unique_together": {("recipe", "style")},
            },
        ),
    ]
