# Generated by Django 5.2.17 on 2026-10-03 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="namn"),
                ),
            ],
            options={
                "verbose_name": "tagg",
                "verbose_name_plural": "taggar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titel")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="beskrivning"),
                ),
                (
                    "servings",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="portioner"
                    ),
                ),
                (
                    "prep_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="förberedelse (min)"
                    ),
                ),
                (
                    "cook_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="tillagning (min)"
                    ),
                ),
                (
                    "ingredients",
                    models.TextField(
                        blank=True,
                        help_text="En ingrediens per rad.",
                        verbose_name="ingredienser",
                    ),
                ),
                (
                    "steps",
                    models.TextField(
                        blank=True, help_text="Ett steg per rad.", verbose_name="gör så"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="anteckningar")),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="källa (bok/länk)"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="recipes/%Y/%m/", verbose_name="bild"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Privat"),
                            ("shared", "Delad"),
                            ("public", "Offentlig"),
                        ],
                        default="private",
                        max_length=10,
                        verbose_name="synlighet",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="skapad"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="ändrad"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ägare",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recipes",
                        to="recipes.tag",
                        verbose_name="taggar",
                    ),
                ),
            ],
            options={
                "verbose_name": "recept",
                "verbose_name_plural": "recept",
                "ordering": ["title"],
            },
        ),
    ]
